import 'package:flutter/material.dart';
import 'bluetooth_screen.dart';
import 'scan_screen_v3.dart';
import '../services/bluetooth_service.dart';
import '../services/reading_store.dart';

class GeoScanShell extends StatefulWidget { const GeoScanShell({super.key}); @override State<GeoScanShell> createState()=>_GeoScanShellState(); }
class _GeoScanShellState extends State<GeoScanShell> {
  int index=2; final readings=<Map<String,dynamic>>[]; final bluetooth=BluetoothService(); final store=ReadingStore(); bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { final r=await store.load(); if(!mounted)return; setState((){readings..clear()..addAll(r);loading=false;}); }
  Future<void> _save(Map<String,dynamic> r) async { await store.save(r); if(!mounted)return; setState(()=>readings.insert(0,r)); }
  Future<void> _clear() async { await store.clear(); if(mounted)setState(readings.clear); }
  @override Widget build(BuildContext context){final pages=<Widget>[_HomeTab(onScan:()=>setState(()=>index=2),onBluetooth:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const BluetoothScreen()))),_LogsTab(readings:readings,onClear:_clear),ScanScreenV3(onSaved:_save),_AnalysisTab(readings:readings),_SettingsTab(bluetooth:bluetooth)];return Scaffold(backgroundColor:const Color(0xFF020711),body:loading?const Center(child:CircularProgressIndicator(color:Colors.cyanAccent)):IndexedStack(index:index,children:pages),bottomNavigationBar:_BottomNav(index:index,onChanged:(v)=>setState(()=>index=v)));}
}
class _BottomNav extends StatelessWidget{const _BottomNav({required this.index,required this.onChanged});final int index;final ValueChanged<int> onChanged;@override Widget build(BuildContext c){const labels=['الرئيسية','السجلات','المسح','التحليل','الإعدادات'];const icons=[Icons.home_rounded,Icons.folder_rounded,Icons.radar,Icons.bar_chart_rounded,Icons.settings_rounded];return Container(padding:const EdgeInsets.fromLTRB(7,6,7,8),decoration:const BoxDecoration(color:Color(0xFF06101D),border:Border(top:BorderSide(color:Color(0xFF183040)))),child:Row(children:List.generate(5,(i){final s=index==i;return Expanded(child:InkWell(onTap:()=>onChanged(i),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icons[i],color:s?Colors.cyanAccent:Colors.white54,size:s&&i==2?30:25),const SizedBox(height:2),Text(labels[i],style:TextStyle(color:s?Colors.cyanAccent:Colors.white60,fontSize:11,fontWeight:s?FontWeight.bold:FontWeight.normal))])));})));}}
class _HomeTab extends StatelessWidget{const _HomeTab({required this.onScan,required this.onBluetooth});final VoidCallback onScan,onBluetooth;@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const SizedBox(height:10),const Text('GeoScan AI',textAlign:TextAlign.center,style:TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const Text('نظام تحليل الإشارات الأرضية',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70,fontSize:16)),const SizedBox(height:24),Container(height:190,decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),gradient:const LinearGradient(colors:[Color(0xFF0A2836),Color(0xFF07111F)])),child:const Center(child:Icon(Icons.radar,size:110,color:Colors.cyanAccent))),const SizedBox(height:20),SizedBox(height:58,child:FilledButton.icon(onPressed:onScan,icon:const Icon(Icons.radar),label:const Text('فتح المسح المباشر'))),const SizedBox(height:12),SizedBox(height:58,child:OutlinedButton.icon(onPressed:onBluetooth,icon:const Icon(Icons.bluetooth),label:const Text('الاتصال بجهاز ESP32'))),const SizedBox(height:18),const _InfoBox('البيانات الحقيقية تأتي من ESP32 عبر Bluetooth. التطبيق لا يختلق نوع معدن أو عمقًا غير مرسل من الجهاز.')]));}
class _LogsTab extends StatelessWidget{const _LogsTab({required this.readings,required this.onClear});final List<Map<String,dynamic>> readings;final VoidCallback onClear;@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,14,16,4),child:Row(children:[const Expanded(child:Text('السجلات',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold))),if(readings.isNotEmpty)IconButton(onPressed:onClear,icon:const Icon(Icons.delete_outline),tooltip:'مسح السجلات')])),Expanded(child:readings.isEmpty?const Center(child:_InfoBox('لا توجد قراءات محفوظة بعد.')):ListView.builder(padding:const EdgeInsets.all(16),itemCount:readings.length,itemBuilder:(_,i){final r=readings[i];return Card(color:const Color(0xFF07111F),child:ListTile(leading:const Icon(Icons.radar,color:Colors.cyanAccent),title:Text('إشارة ${_num(r['signal']).toStringAsFixed(1)}%'),subtitle:Text('استقرار ${_num(r['stability']).toStringAsFixed(0)}% • عمق ${_num(r['depth']).toStringAsFixed(2)} m\nالهدف: ${r['target']??'غير محدد'}'),isThreeLine:true));}))]));}
class _AnalysisTab extends StatelessWidget{const _AnalysisTab({required this.readings});final List<Map<String,dynamic>> readings;@override Widget build(BuildContext c){if(readings.isEmpty)return const SafeArea(child:Center(child:_InfoBox('التحليل يحتاج قراءة محفوظة من ESP32.')));final sig=readings.map((r)=>_num(r['signal'])).toList();final avg=sig.reduce((a,b)=>a+b)/sig.length;final peak=sig.reduce((a,b)=>a>b?a:b);final st=readings.map((r)=>_num(r['stability'])).reduce((a,b)=>a+b)/readings.length;final last=readings.first;return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('التحليل',textAlign:TextAlign.center,style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:16),_metric('عدد القراءات','${readings.length}',Colors.cyanAccent),_metric('متوسط الإشارة','${avg.toStringAsFixed(1)}%',Colors.greenAccent),_metric('أعلى إشارة','${peak.toStringAsFixed(1)}%',Colors.orangeAccent),_metric('متوسط الاستقرار','${st.toStringAsFixed(1)}%',Colors.cyanAccent),_metric('آخر عمق مرسل','${_num(last['depth']).toStringAsFixed(2)} m',Colors.greenAccent),_metric('آخر هدف مرسل','${last['target']??'غير محدد'}',Colors.white),const SizedBox(height:12),const _InfoBox('هذا تحليل إحصائي للبيانات الفعلية المحفوظة. تحديد الذهب أو معدن بعينه يحتاج خوارزمية مدعومة ببيانات ومعايرة حقيقية من الحساس؛ لذلك لا نعرض نسبًا وهمية.')]));}Widget _metric(String a,String b,Color c)=>Card(color:const Color(0xFF07111F),child:ListTile(title:Text(a),trailing:Text(b,style:TextStyle(color:c,fontSize:19,fontWeight:FontWeight.bold))));}
class _SettingsTab extends StatefulWidget{const _SettingsTab({required this.bluetooth});final BluetoothService bluetooth;@override State<_SettingsTab> createState()=>_SettingsTabState();}
class _SettingsTabState extends State<_SettingsTab>{bool audio=true,vibration=true;double sensitivity=75;String filter='متوسطة';@override Widget build(BuildContext c){final connected=widget.bluetooth.isConnected;return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const Text('الإعدادات',textAlign:TextAlign.center,style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:12),Card(color:const Color(0xFF07111F),child:Column(children:[ListTile(leading:Icon(Icons.bluetooth,color:connected?Colors.greenAccent:Colors.redAccent),title:const Text('Bluetooth'),subtitle:Text(connected?'متصل بجهاز GeoScan-AI':'غير متصل')),ListTile(title:const Text('الحساسية'),subtitle:Slider(value:sensitivity,min:0,max:100,divisions:100,onChanged:connected?(v){setState(()=>sensitivity=v);widget.bluetooth.setSensitivity(v);}:null),trailing:Text('${sensitivity.toStringAsFixed(0)}%')),ListTile(title:const Text('الفلترة'),trailing:DropdownButton<String>(value:filter,items:const ['منخفضة','متوسطة','عالية'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:connected?(v){if(v!=null){setState(()=>filter=v);widget.bluetooth.setFilter(v);}}:null)),SwitchListTile(title:const Text('التنبيه الصوتي'),value:audio,onChanged:connected?(v)async{if(await widget.bluetooth.setAudio(v))setState(()=>audio=v);}:null),SwitchListTile(title:const Text('الاهتزاز'),value:vibration,onChanged:connected?(v)async{if(await widget.bluetooth.setVibration(v))setState(()=>vibration=v);}:null)])),const SizedBox(height:12),const _InfoBox('المعايرة والحماية الكهربائية جزء من الجهاز الميداني. لا توصل البطارية مباشرة إلى ESP32.') ]));}}
class _InfoBox extends StatelessWidget{const _InfoBox(this.text);final String text;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF07111F),borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.cyanAccent.withValues(alpha:.18))),child:Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70,height:1.5)));}
double _num(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;
