import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../services/bluetooth_service.dart';

class ScanScreenV3 extends StatefulWidget {
  const ScanScreenV3({super.key, this.onSaved});
  final ValueChanged<Map<String, dynamic>>? onSaved;
  @override State<ScanScreenV3> createState() => _ScanScreenV3State();
}

class _ScanScreenV3State extends State<ScanScreenV3> {
  final bt = BluetoothService();
  final List<double> samples = <double>[];
  StreamSubscription<String>? dataSub;
  StreamSubscription<bool>? connSub;
  double signal=0, raw=0, stability=0, depth=0, sensitivity=75;
  bool connected=false, scanning=false, calibrating=false, audio=true, vibration=true;
  String filter='متوسطة', status='غير متصل', target='غير محدد';
  DateTime? lastData;

  @override void initState(){ super.initState(); connected=bt.isConnected; status=connected?'متصل':'غير متصل'; dataSub=bt.dataStream.listen(_onData); connSub=bt.connectionStream.listen((v){if(!mounted)return;setState((){connected=v;status=v?'متصل':'غير متصل';if(!v)scanning=false;});}); }
  @override void dispose(){dataSub?.cancel();connSub?.cancel();super.dispose();}

  double _n(Map<String,dynamic> d,List<String> keys,double f){for(final k in keys){final v=d[k];if(v is num)return v.toDouble();final p=double.tryParse('${v??''}'.replaceAll(',','.'));if(p!=null&&p.isFinite)return p;}return f;}
  void _onData(String text){if(!mounted||text.trim().isEmpty)return;Map<String,dynamic> d={};try{final x=jsonDecode(text.trim());if(x is Map)d=Map<String,dynamic>.from(x);}catch(_){final n=double.tryParse(text.trim().replaceAll(',','.'));if(n!=null)d={'signal':n};}if(d.isEmpty)return;
    final ns=_n(d,['signal','value','strength','reading'],signal).clamp(0,100).toDouble();
    setState((){signal=signal==0?ns:(signal*.7+ns*.3).clamp(0,100).toDouble();raw=_n(d,['raw','rawSignal'],raw);stability=_n(d,['stability','stable'],stability).clamp(0,100).toDouble();depth=math.max(0,_n(d,['depth','distance'],depth));final s='${d['status']??''}'.trim();status=s.isEmpty?(d['scanning']==true?'يمسح':'متصل'):s;scanning=d['scanning']==true||s=='يمسح'||s.toLowerCase()=='scanning';final t='${d['target']??''}'.trim();if(t.isNotEmpty)target=t;lastData=DateTime.now();if(samples.length>=120)samples.removeAt(0);samples.add(signal);}); }
  bool get recent=>lastData!=null&&DateTime.now().difference(lastData!).inSeconds<3;
  Color get sigColor=>signal<20?Colors.redAccent:signal<40?Colors.orangeAccent:signal<65?Colors.amberAccent:Colors.greenAccent;
  String get quality=>!connected?'غير متصل':calibrating?'جاري المعايرة':scanning&&!recent?'بانتظار بيانات ESP32':!scanning?'جاهز للمسح':signal<20?'ضعيفة':signal<40?'متوسطة':signal<65?'جيدة':signal<85?'قوية':'قوية جدًا';
  void msg(String s){if(!mounted)return;ScaffoldMessenger.of(context)..hideCurrentSnackBar()..showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));}
  Future<void> start()async{if(!connected){msg('اتصل بجهاز ESP32 أولًا');return;}final ok=await bt.startScan();if(ok&&mounted)setState((){scanning=true;status='يمسح';samples.clear();});msg(ok?'بدأ المسح':'تعذر بدء المسح');}
  Future<void> stop()async{final ok=await bt.stopScan();if(ok&&mounted)setState((){scanning=false;status='متوقف';});msg(ok?'تم إيقاف المسح':'تعذر إيقاف المسح');}
  Future<void> calibrate()async{if(!connected){msg('اتصل بجهاز ESP32 أولًا');return;}if(scanning){msg('أوقف المسح أولًا');return;}setState(()=>calibrating=true);final ok=await bt.calibrate();if(mounted)setState(()=>calibrating=false);msg(ok?'تم إرسال أمر المعايرة':'تعذر إرسال المعايرة');}
  void save(){if(!connected){msg('الجهاز غير متصل');return;}if(lastData==null){msg('لا توجد قراءة مستلمة');return;}widget.onSaved?.call({'time':DateTime.now().toIso8601String(),'signal':signal,'raw':raw,'stability':stability,'depth':depth,'target':target,'status':status,'sensitivity':sensitivity,'filter':filter});HapticFeedback.mediumImpact();msg('تم حفظ القراءة');}
  BoxDecoration box()=>BoxDecoration(color:const Color(0xFF07111F),borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.cyanAccent.withValues(alpha:.18)));

  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF020711),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(16,8,16,20),children:[header(),gauge(),cards(),bar(),chart(),analysis(),statusRow(),actions(),controls(),note()]));
  Widget header()=>Row(children:[const Icon(Icons.radar,color:Colors.cyanAccent,size:30),const Expanded(child:Column(children:[Text('GeoScan AI',style:TextStyle(fontSize:25,fontWeight:FontWeight.w800)),Text('المسح المباشر',style:TextStyle(color:Colors.white70))])),Icon(Icons.bluetooth,color:connected?Colors.greenAccent:Colors.redAccent),const SizedBox(width:6),Text(connected?'متصل':'غير متصل',style:TextStyle(color:connected?Colors.greenAccent:Colors.redAccent))]);
  Widget gauge()=>SizedBox(height:255,child:Stack(alignment:Alignment.center,children:[CustomPaint(size:const Size(double.infinity,245),painter:_Gauge(signal)),Positioned(top:92,child:Column(children:[const Text('LIVE SCAN',style:TextStyle(fontSize:18,letterSpacing:1.1)),Text('${signal.toStringAsFixed(1)}%',style:TextStyle(fontSize:52,fontWeight:FontWeight.w800,color:sigColor)),Text(quality,style:TextStyle(color:sigColor,fontWeight:FontWeight.bold))]))]));
  Widget card(String t,String v,String sub,Color c,IconData i)=>Container(padding:const EdgeInsets.all(12),decoration:box(),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:Colors.white,size:22),Text(t,style:const TextStyle(color:Colors.white70,fontSize:12)),Text(v,style:TextStyle(color:c,fontSize:23,fontWeight:FontWeight.bold)),Text(sub,style:TextStyle(color:c.withValues(alpha:.8),fontSize:11))]));
  Widget cards()=>Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:card('شدة الإشارة','${signal.toStringAsFixed(1)}%',quality,sigColor,Icons.graphic_eq)),const SizedBox(width:8),Expanded(child:Column(children:[card('العمق التقديري',depth>0?'${depth.toStringAsFixed(2)} m':'--','من ESP32',Colors.greenAccent,Icons.gps_fixed),const SizedBox(height:8),card('الاستقرار','${stability.toStringAsFixed(0)}%','من ESP32',Colors.cyanAccent,Icons.multiline_chart)]))]);
  Widget bar()=>Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:Column(children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('0'),Text('20'),Text('40'),Text('60'),Text('80'),Text('100')]),const SizedBox(height:7),ClipRRect(borderRadius:BorderRadius.circular(10),child:LinearProgressIndicator(value:signal/100,minHeight:14,backgroundColor:Color(0xFF17202D),color: sigColor))]));
  Widget chart()=>Container(height:205,margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('حركة الإشارة',textAlign:TextAlign.right,style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:6),Expanded(child:CustomPaint(painter:_Chart(samples)))]));
  Widget analysis(){final peak=samples.isEmpty?0:samples.reduce(math.max);final avg=samples.isEmpty?0:samples.reduce((a,b)=>a+b)/samples.length;return Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('التحليل الفعلي للقراءة',textAlign:TextAlign.right,style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),_row('متوسط الإشارة','${avg.toStringAsFixed(1)}%'),_row('أعلى إشارة','${peak.toStringAsFixed(1)}%'),_row('الخام Raw','${raw.toStringAsFixed(2)}'),_row('استقرار الإشارة','${stability.toStringAsFixed(1)}%'),_row('الهدف من ESP32',target),const SizedBox(height:6),Text(target=='غير محدد'?'نوع المعدن غير متاح: ESP32 لم يرسل تعريفًا موثوقًا للهدف. لا يتم اختلاق نسب ذهب/فضة/حديد.':'الهدف المرسل من ESP32: $target',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70,height:1.4))]));}
  Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a,style:const TextStyle(color:Colors.white70)),Text(b,style:const TextStyle(fontWeight:FontWeight.bold,color:Colors.cyanAccent))]));
  Widget statusRow()=>Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:Wrap(spacing:12,runSpacing:7,children:[Text('الحالة: $status'),Text('الحساسية: ${sensitivity.toStringAsFixed(0)}%'),Text('الفلترة: $filter'),Text('بيانات: ${recent?'LIVE':'انتظار'}',style:TextStyle(color:recent?Colors.greenAccent:Colors.orangeAccent))]));
  Widget actions()=>Padding(padding:const EdgeInsets.only(top:10),child:Row(children:[Expanded(child:ElevatedButton.icon(onPressed:scanning?null:start,icon:const Icon(Icons.play_arrow),label:const Text('بدء'),style:ElevatedButton.styleFrom(backgroundColor:const Color(0xFF123D22),foregroundColor:Colors.greenAccent,padding:const EdgeInsets.symmetric(vertical:15)))),const SizedBox(width:7),Expanded(child:ElevatedButton.icon(onPressed:scanning?stop:null,icon:const Icon(Icons.stop),label:const Text('إيقاف'),style:ElevatedButton.styleFrom(backgroundColor:const Color(0xFF42161B),foregroundColor:Colors.redAccent,padding:const EdgeInsets.symmetric(vertical:15)))),const SizedBox(width:7),Expanded(child:ElevatedButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('حفظ'),style:ElevatedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:15))))]));
  Widget controls()=>Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:Column(children:[Row(children:[Expanded(child:Text('الحساسية ${sensitivity.toStringAsFixed(0)}%')),Expanded(child:Slider(value:sensitivity,min:0,max:100,divisions:100,onChanged:connected?(v){setState(()=>sensitivity=v);bt.setSensitivity(v);}:null))]),Row(children:[const Expanded(child:Text('الفلترة')),DropdownButton<String>(value:filter,items:const ['منخفضة','متوسطة','عالية'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:connected?(v){if(v!=null){setState(()=>filter=v);bt.setFilter(v);}}:null)]),SwitchListTile(title:const Text('التنبيه الصوتي'),value:audio,onChanged:connected?(v)async{if(await bt.setAudio(v))setState(()=>audio=v);}:null),SwitchListTile(title:const Text('الاهتزاز'),value:vibration,onChanged:connected?(v)async{if(await bt.setVibration(v))setState(()=>vibration=v);}:null),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:calibrating?null:calibrate,icon:const Icon(Icons.tune),label:Text(calibrating?'جاري المعايرة...':'معايرة الجهاز')))]));
  Widget note()=>Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:box(),child:const Text('مهم: العمق ونوع الهدف لا يصبحان قياسًا حقيقيًا إلا إذا أرسل ESP32 بيانات معايرة مناسبة. التطبيق يعرض البيانات الواردة ولا يخترع نتائج معدن غير موجودة.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70,height:1.5)));
}

class _Gauge extends CustomPainter{_Gauge(this.v);final double v;@override void paint(Canvas c,Size s){final center=Offset(s.width/2,s.height*.82);final r=math.min(s.width*.43,s.height*.7);final rect=Rect.fromCircle(center:center,radius:r);const st=math.pi*1.08,sw=math.pi*.84;final base=Paint()..style=PaintingStyle.stroke..strokeWidth=22..color=const Color(0xFF18212B);c.drawArc(rect,st,sw,false,base);final col=v<20?Colors.redAccent:v<40?Colors.orangeAccent:v<65?Colors.amberAccent:Colors.greenAccent;final p=Paint()..style=PaintingStyle.stroke..strokeWidth=22..color=col;c.drawArc(rect,st,sw*(v/100),false,p);final a=st+sw*v/100;final end=Offset(center.dx+r*.75*math.cos(a),center.dy+r*.75*math.sin(a));c.drawLine(center,end,Paint()..color=col..strokeWidth=5..strokeCap=StrokeCap.round);c.drawCircle(center,7,Paint()..color=Colors.white);}@override bool shouldRepaint(covariant _Gauge o)=>o.v!=v;}
class _Chart extends CustomPainter{_Chart(this.v);final List<double> v;@override void paint(Canvas c,Size s){final g=Paint()..color=const Color(0xFF1A2A38)..strokeWidth=1;for(int i=0;i<=4;i++){final y=s.height*i/4;c.drawLine(Offset(0,y),Offset(s.width,y),g);}if(v.length<2)return;final p=Path();for(int i=0;i<v.length;i++){final x=s.width*i/(v.length-1),y=s.height*(1-v[i].clamp(0,100)/100);i==0?p.moveTo(x,y):p.lineTo(x,y);}c.drawPath(p,Paint()..style=PaintingStyle.stroke..strokeWidth=3..color=Colors.greenAccent);}@override bool shouldRepaint(covariant _Chart o)=>o.v!=v;}
